### PR TITLE
feat: Extract correct type and value from top-most error

### PR DESCRIPTION
**Pull request by kamilogorek**
Fixes https://github.com/getsentry/sentry-go/issues/70 cc @mfridman @fedoricobond

### CODE REVIEW

**Comment by matianjun1** [comment]
for v0.6.1 how about this feature?

**Comment by kamilogorek** [comment]
I'm not sure what is the question here. We already shipped this change a long time ago.

**Comment by matianjun1** [comment]
> I'm not sure what is the question here. We already shipped this change a long time ago.

@kamilogorek Sorry for my description. For the newest release. This feature has been remvoed. Both of the test code.

https://github.com/getsentry/sentry-go/blob/af3076c5259eb407873c99da142af3ee29051105/client_test.go#L125-L143

This should be `*sentry.customErr` not `"*errors.withStack`

**Comment by rhcarvalho** [comment]
@matianjun1 in v0.6.0 we added full support for chained errors, see https://github.com/getsentry/sentry-go/pull/185.

Now we report a complete chain of errors, as supported in other platforms and described here: https://develop.sentry.dev/sdk/event-payloads/exception/.

If you found a bug or have a feature request, please [open a new issue](https://github.com/getsentry/sentry-go/issues/new/choose).

**Pull request merged**
