### PR TITLE
Allow custom stacktrace extraction

### PR DESCRIPTION
**Pull request by flimzy**
This PR makes it possible to use a custom stack-trace extractor function.  There was a TODO comment suggesting this as a possible feature, and I've found we need this feature, so I added it.

I look forward to any feedback.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
> I've found we need this feature

Are you using an open source error type that is not yet handled in `ExtractStacktrace`?

**Comment by flimzy** [comment]
> Are you using an open source error type that is not yet handled in `ExtractStacktrace`?

No. The biggest thing I need is to change _which_ stack trace is extracted.

Consider a case where you have multiple wrapped errors. The current implementation extracts the outter-most stack trace. We typically need the inner-most.

Example:

```
func foo() error {
    return errors.New("failure!")
}

func bar() error {
    if err := foo(); err != nil {
        return errors.WithStack(err)
    }
}

func baz() eror {
    if err := bar(); err != nil {
        return errors.WithStack(err)
    }
}
```

If we then log the error returned by `baz`, the default behavior will show us the stack from `baz`. We need the stack from `bar`. Providing our own `ExtractStacktrace` implementation makes this possible.

**Comment by rhcarvalho** [comment]
@flimzy what version of the SDK are you using? In 0.6.0, we added support for reporting a complete chain of errors, and that should include the stack for each error in the chain if the stacktrace is available.

**Comment by flimzy** [comment]
> @flimzy what version of the SDK are you using? In 0.6.0, we added support for reporting a complete chain of errors, and that should include the stack for each error in the chain if the stacktrace is available.

We are using 0.6.0, but not yet everywhere.  I was not aware of that new feature. That would probably be sufficient for my needs. Thanks for letting me know.

**Pull request closed without merging**
