### PR TITLE
Add Fiber integration

### PR DESCRIPTION
**Pull request by arsmn**
[Fiber](https://github.com/gofiber/fiber) integration

### CODE REVIEW

**Comment by arsmn** [comment]
@rhcarvalho

**Comment by rhcarvalho** [comment]
@arsmn thanks for the contribution. Sorry we haven't had the bandwidth to review this yet.
On a high level I expect this is pretty much the same as the fasthttp integration with types adapted to match fiber's.

I'll have a look at this and Buffalo (https://github.com/getsentry/sentry-go/pull/196) in the coming weeks, perhaps start moving integrations off into their own modules to avoid an ever increasing list of deps in the main go.mod file.

**Comment by akshaybabloo** [comment]
@rhcarvalho gentle ping

**Comment by anistark** [comment]
@rhcarvalho Can we please merge this ?

**Comment by th0th** [comment]
Any updates on this? 💐

**Comment by alizaya** [comment]
any news?

**Comment by ciazhar** [comment]
@rhcarvalho any update ?

**Comment by efectn** [comment]
Any update?

**Comment by pateljoel** [comment]
Would be nice if this was merged in with official support for Fiber and Sentry. 
Are there any issues @rhcarvalho?

**Comment by DuginKim** [comment]
any update? 
plz

**Comment by NoobTW** [comment]
Ping generally

**Comment by rodrigoodhin** [comment]
any update?
plz

**Comment by fcarvalhido** [comment]
Ping and Pong, please.

**Comment by DuginKim** [comment]
not yet?

**Comment by DuginKim** [comment]
not yet2?

@rhcarvalho @kamilogorek @benvinegar

**Comment by sebastianbuechler** [comment]
> @arsmn thanks for the contribution. Sorry we haven't had the bandwidth to review this yet. On a high level I expect this is pretty much the same as the fasthttp integration with types adapted to match fiber's.
> 
> I'll have a look at this and Buffalo (#196) in the coming weeks, perhaps start moving integrations off into their own modules to avoid an ever increasing list of deps in the main go.mod file.

This is open for 1.5 years now. Is this still on the road map?

**Comment by efectn** [comment]
I think @arsmn should create PR under the https://github.com/gofiber/contrib.

**Comment by arsmn** [comment]
Fiber integration is now available https://github.com/gofiber/contrib/tree/main/fibersentry
Thank you all

**Comment by cleptric** [comment]
Hey @arsmn 
Are you still interested in getting this merged?

**Comment by robd003** [comment]
Hey @cleptric & @arsmn any chance we could get this merged in? I'd love to have Sentry officially support this!

**Comment by cleptric** [comment]
@robd003 Adding a Fiber integration is definitely on our road map, but I can't provide you with an ETA when this may land.

**Comment by alfawal** [comment]
@cleptric Kind reminder 🙏🏻

**Comment by vaind** [comment]
Updated to work with the latest main branch in #795

**Comment by vaind** [comment]
Thanks @arsmn for the contribution and sorry it took so long to get merged.

**Pull request closed without merging**
