### PR TITLE
feat: add support for stack trace from github.com/pierrre/errors

### PR DESCRIPTION
**Pull request by pierrre**
Related to https://github.com/getsentry/sentry-go/issues/253#issuecomment-1284034722

### CODE REVIEW

**Comment by cleptric** [comment]
I'm sorry, but we can't get this merged.
We only support libraries that are frequently used in the ecosystem.
Can you work around this by creating your own integration?

**Review by cleptric — CHANGES_REQUESTED** [review]
I'm sorry, but we can't get this merged.
We only support libraries that are frequently used in the ecosystem.
Can you work around this by creating your own integration?

**Comment by pierrre** [comment]
I'm willing to write the code that will add support for custom stack trace.
I just need to know what is an acceptable solution (the "user interface")

**Comment by flimzy** [comment]
What if you make `github.com/pierrre/errors` support `github.com/pkg/errors` stack traces?  I believe it would be a fairly simple change to add a `Stacktrace() errors.Stacktrace` method on the errors in that package, no?  (See https://pkg.go.dev/github.com/pkg/errors#hdr-Retrieving_the_stack_trace_of_an_error_or_wrapper)

**Pull request closed without merging**
