### PR TITLE
ref: Rename ClientOptions.SendDefaultPii to ClientOptions.SendDefaultPII

### PR DESCRIPTION
**Pull request by cleptric**
re: https://github.com/getsentry/sentry-go/pull/485#discussion_r1011500255

### CODE REVIEW

**Review by AbhiPrasad — COMMENTED** [review]
I understand this helps unify with the Go ecosystem - but in this case we use the lowercase version of `SendDefaultPii` in every single other SDK, I'd rather stay consistent with the rest of the SDK

**Comment by cleptric** [comment]
I think it's ok to stay unified with the Go ecosystem, especially if we expand on better linting in the future.
In terms of DevEx, IDEs should autocomplete on this just fine.

**Review by AbhiPrasad — APPROVED** [review]
We'll have to update the docs about this as well then!

**Comment by cleptric** [comment]
Yes Sir! https://github.com/getsentry/sentry-docs/pull/5708

**Pull request merged**
