### PR TITLE
ci(travis): Don't execute Travis since we now have GH actions

### LINKED ISSUE #313: Migrate CI from Travis to GitHub Actions
Travis sprung some surprise billing changes on us awhile, so we are now prioritizing removing usage of TravisCI completely. This issue will be used by @getsentry/productivity to track overall progress across the organization, but please let us know here if there's anything we should be aware of.

### PR DESCRIPTION
**Pull request by armenzg**
Fixes #313

### CODE REVIEW

**Comment by armenzg** [comment]
@rhcarvalho feel free to merge when convenient.
You would need to change the Required Checks.
image

**Comment by rhcarvalho** [comment]
Thanks @armenzg !

**Comment by rhcarvalho** [comment]
Going to wait a few PRs to gain confidence on GHA.

**Comment by armenzg** [comment]
Thank you!

**Pull request merged**
