### PR TITLE
feat: make other dependencies into submodules (#156)

### PR DESCRIPTION
**Pull request by hidu**
go1.17- also can works
keep the original dependency version

### CODE REVIEW

**Comment by kamilogorek** [comment]
There is apparently one redundant line in `go.mod` here: https://github.com/getsentry/sentry-go/pull/414/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R13

**Comment by hidu** [comment]
> There is apparently one redundant line in go.mod

deleted

**Comment by marco-bianchi-bee** [comment]
Hello @kamilogorek , do you have any updates about this? I got several CVE notifications just because this sdk has kataras/iris as a direct dependency, a submodule structure would so much cleaner.

**Comment by kamilogorek** [comment]
@marco-bianchi-bee what version of Go are you using? Since `1.17`, you should be able to use https://go.dev/ref/mod#graph-pruning

Once `1.19` releases (should be early August), I'll try to spend some time on this repo and refresh it a bit, as I'm not owning it anymore at the current time.

**Comment by marco-bianchi-bee** [comment]
@kamilogorek thank you for your answer I am using `1.18` so my go.mod and my go.sum look good, but the tool we use (snyk) probably uses `go list -m all` and so it catches also the dependencies of the dependencies. I am looking forward to the next release:)

**Comment by kamilogorek** [comment]
@marco-bianchi-bee snyk is using `go list -json -deps` (https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-golang), however, I checked and you are right about it picking up `iris`.
The original issue in the framework itself has been fixed, but `12.2` is in the beta stage now, so I will update once it's out and the snyk issue will be gone as well.

**Comment by marco-bianchi-bee** [comment]
@kamilogorek hello any progress on this? I had to remove sentry as a dependency because the security issues keep piling up.

**Comment by kamilogorek** [comment]
@marco-bianchi-bee security issues should be resolved in `0.14.0`

**Pull request closed without merging**
